# Generated by Django 5.1.1 on 2024-09-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=225)),
                ('author', models.CharField(max_length=225)),
                ('genre', models.CharField(max_length=225)),
                ('language', models.CharField(max_length=225)),
                ('quantity', models.IntegerField(max_length=10)),
                ('published', models.IntegerField(max_length=10)),
            ],
        ),
    ]
